### ISSUE TITLE
Display UTF-8 

### ISSUE THREAD

**Issue by vigliensoni** [ismir/ISMIR-Conf#1]
Make sure the site renders UTF-8 character set.

See how the site is currently rendering latin accents:

<img width="883" alt="Screen Shot 2020-09-16 at 2 04 03 PM" src="https://user-images.githubusercontent.com/492229/93374972-7b0ab880-f825-11ea-9f20-1a577fb0f619.png">

**Comment by evansavage** [comment]
I emailed you about this. I have started exploring solutions for converting the CSV data from MACROMAN to UTF-8, with no luck so far using the _iconv_ terminal command. It would be very useful if you could specify the encoding before converting the spreadsheet format.
